name: Workflow com IPs Diferentes

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Configurar Proxy (IP 1)
        run: |
          echo "Usando IP 1"
          curl -x http://ifconfig.me

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Configurar Proxy (IP 2)
        run: |
          echo "Usando IP 2"
          curl -x http://ifconfig.me
